<div class="wg-page" dir="rtl">
    <div class="wg-page-head"><div><h1 class="wg-title">واتساب</h1><div class="wg-subtitle">قواعد تلقائية، تشغيل يدوي، قوالب ورسائل مرسلة</div></div><button wire:click="openCreate" class="wg-btn wg-btn-primary">＋ قاعدة جديدة</button></div>
    @include('livewire.admin._tabs')
    @if(session('success'))<div class="wg-flash">{{ session('success') }}</div>@endif
    @if(!$configured)<div class="wg-errors" style="border-color:#5b4815;color:#ffbd38;background:#241a06">واجهة WhatsApp Cloud API غير مهيأة. يمكنك تجهيز القواعد الآن، ولن يتم الإرسال حتى تضيف بيانات API.</div>@endif
    @if($errors->has('whatsapp'))<div class="wg-errors">{{ $errors->first('whatsapp') }}</div>@endif

    <div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px">@foreach([['إجمالي القواعد',$stats['rules'],'wg-blue'],['قواعد مفعلة',$stats['active'],'wg-green'],['مرسلة',$stats['sent'],'wg-purple'],['فاشلة',$stats['failed'],'wg-red']] as [$l,$v,$c])<div class="wg-card wg-stat"><small>{{ $l }}</small><strong class="{{ $c }}">{{ $v }}</strong></div>@endforeach</div>

    <div class="wg-card wg-card-pad">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><div><h2 class="wg-section-title">قواعد الإرسال</h2><div class="wg-muted" style="font-size:10px;margin-top:4px">قرب الانتهاء، انتهاء الاشتراك، وإعادة التنشيط.</div></div><span class="wg-badge {{ $configured ? 'wg-badge-green' : 'wg-badge-orange' }}">{{ $configured ? 'API جاهز' : 'بانتظار الربط' }}</span></div>
        <div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px">
            @forelse($rules as $r)
                <div class="wg-finance-box">
                    <div style="display:flex;justify-content:space-between;gap:8px"><div><strong style="font-size:12px">{{ $r->name }}</strong><div class="wg-muted" style="font-size:9px;margin-top:3px">{{ match($r->type){'near_expiry'=>'قرب انتهاء الاشتراك','expired'=>'انتهاء الاشتراك','reactivation'=>'إعادة تنشيط عضو',default=>$r->type} }}</div></div><span class="wg-badge {{ $r->is_enabled ? 'wg-badge-green' : 'wg-badge-red' }}">{{ $r->is_enabled ? 'مفعلة' : 'متوقفة' }}</span></div>
                    <div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:12px"><div><span>الوضع</span><strong style="font-size:11px">{{ $r->mode === 'auto' ? 'تلقائي' : 'يدوي' }}</strong></div><div><span>المجموعة</span><strong style="font-size:11px">{{ $r->audience === 'all' ? 'الكل' : ($r->audience === 'women' ? 'نساء' : 'رجال') }}</strong></div></div>
                    <div class="wg-muted" style="font-size:9px;line-height:1.7;margin-top:10px;height:46px;overflow:hidden">{{ $r->message_template ?: 'قالب Meta: '.$r->template_name }}</div>
                    <div class="wg-divider" style="margin:12px 0"></div><div style="display:flex;gap:5px;flex-wrap:wrap"><button wire:click="edit({{ $r->id }})" class="wg-btn wg-btn-sm">تعديل</button><button wire:click="toggle({{ $r->id }})" class="wg-btn wg-btn-sm">{{ $r->is_enabled ? 'إيقاف' : 'تفعيل' }}</button><button wire:click="run({{ $r->id }})" wire:confirm="تشغيل هذه القاعدة الآن؟" class="wg-btn wg-btn-sm wg-btn-success">تشغيل الآن</button><button wire:click="delete({{ $r->id }})" wire:confirm="حذف القاعدة؟" class="wg-btn wg-btn-sm wg-btn-danger">حذف</button></div>
                </div>
            @empty<div class="wg-muted">لا توجد قواعد.</div>@endforelse
        </div>
    </div>

    <div class="wg-card"><div class="wg-card-pad"><h2 class="wg-section-title">سجل الرسائل</h2></div><div class="wg-table-wrap" style="border:0;border-top:1px solid var(--wg-border);border-radius:0"><table class="wg-table"><thead><tr><th>الهاتف</th><th>الحالة</th><th>الوضع</th><th>وقت الإرسال</th><th>الخطأ</th></tr></thead><tbody>@forelse($messages as $m)<tr><td dir="ltr">{{ $m->phone }}</td><td><span class="wg-badge {{ $m->status==='sent' ? 'wg-badge-green' : ($m->status==='failed' ? 'wg-badge-red' : 'wg-badge-orange') }}">{{ $m->status }}</span></td><td>{{ $m->mode }}</td><td>{{ $m->sent_at ?: '—' }}</td><td class="wg-red">{{ $m->error_message ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="wg-muted">لا توجد رسائل بعد.</td></tr>@endforelse</tbody></table></div></div>

    @if($showEditor)
    <div class="wg-modal-backdrop"><div class="wg-modal wg-modal-lg"><div class="wg-modal-head"><h2 class="wg-section-title">{{ $editingId ? 'تعديل قاعدة واتساب' : 'قاعدة واتساب جديدة' }}</h2><button wire:click="$set('showEditor',false)" class="wg-modal-x">×</button></div><form wire:submit="save"><div class="wg-modal-body">@if($errors->any())<div class="wg-errors" style="margin-bottom:14px">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif<div class="wg-two"><div><label class="wg-label">اسم القاعدة *</label><input wire:model="name" class="wg-field"></div><div><label class="wg-label">المحفز *</label><select wire:model="trigger" class="wg-select"><option value="near_expiry">قرب انتهاء الاشتراك</option><option value="expired">انتهاء الاشتراك</option><option value="reactivation">إعادة تنشيط عضو</option></select></div><div><label class="wg-label">عدد الأيام</label><input wire:model="delay_days" type="number" class="wg-field"></div><div><label class="wg-label">المجموعة</label><select wire:model="target_group" class="wg-select"><option value="all">الكل</option><option value="men">رجال</option><option value="women">نساء</option></select></div><div><label class="wg-label">الوضع</label><select wire:model="mode" class="wg-select"><option value="manual">يدوي</option><option value="auto">تلقائي</option></select></div><div><label class="wg-label">لغة القالب</label><input wire:model="template_language" class="wg-field" dir="ltr"></div><div style="grid-column:1/-1"><label class="wg-label">نص الرسالة</label><textarea wire:model="message_template" class="wg-textarea" placeholder="استخدم {name} و {code}"></textarea></div><div style="grid-column:1/-1"><label class="wg-label">اسم قالب Meta المعتمد — اختياري</label><input wire:model="template_name" class="wg-field" dir="ltr"></div></div><label style="display:flex;gap:7px;align-items:center;font-size:11px;margin-top:12px"><input wire:model="is_enabled" type="checkbox"> القاعدة مفعلة</label></div><div class="wg-modal-foot"><button class="wg-btn wg-btn-primary">حفظ القاعدة</button><button type="button" wire:click="$set('showEditor',false)" class="wg-btn">إلغاء</button></div></form></div></div>
    @endif
</div>
